// Copyright 2026 The Lattice Authors, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command gencn regenerates apple/engine/split/data/cn_ipv4.txt from APNIC's
// delegated file. Run it via hack/scripts/gen-cn-lists.sh.
package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/alatticeio/lattice/apple/engine/split"
)

func open(src string) (io.ReadCloser, error) {
	if strings.HasPrefix(src, "http://") || strings.HasPrefix(src, "https://") {
		client := &http.Client{Timeout: 60 * time.Second}
		resp, err := client.Get(src)
		if err != nil {
			return nil, err
		}
		if resp.StatusCode != http.StatusOK {
			_ = resp.Body.Close()
			return nil, fmt.Errorf("GET %s: %s", src, resp.Status)
		}
		return resp.Body, nil
	}
	return os.Open(src)
}

func main() {
	in := flag.String("in", "https://ftp.apnic.net/stats/apnic/delegated-apnic-latest", "APNIC delegated file (URL or path)")
	out := flag.String("out", "apple/engine/split/data/cn_ipv4.txt", "output file")
	flag.Parse()

	r, err := open(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gencn:", err)
		os.Exit(1)
	}
	defer r.Close()

	ranges, err := split.ParseAPNIC(r, "CN")
	if err != nil {
		fmt.Fprintln(os.Stderr, "gencn:", err)
		os.Exit(1)
	}
	merged := split.MergeRanges(ranges)
	var blocks []string
	for _, rg := range merged {
		blocks = append(blocks, split.RangeToCIDRs(rg)...)
	}
	// Route the result through the same parser the engine uses, so the file
	// can never contain a line the engine would drop (reserved space etc.).
	clean := split.ParseCNSet(strings.Join(blocks, "\n")).Routes(0)

	var b strings.Builder
	fmt.Fprintf(&b, "# CN IPv4 blocks, generated by hack/scripts/gen-cn-lists.sh — do not edit by hand.\n")
	fmt.Fprintf(&b, "# source: %s\n", *in)
	fmt.Fprintf(&b, "# generated: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "# apnic records: %d, merged ranges: %d, blocks: %d\n", len(ranges), len(merged), len(clean))
	for _, c := range clean {
		b.WriteString(c)
		b.WriteByte('\n')
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gencn:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s: %d blocks\n", *out, len(clean))
}
