apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lattice.fullname" . }}
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["alattice.io"]
    resources: ["latticenetworks", "latticepeers", "latticepolicies", "latticeglobalippools",
                "latticeenrollmenttokens", "latticerelayservers", "latticeclusterpeerings",
                "latticenetworkpeerings", "latticeendpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["alattice.io"]
    resources: ["latticenetworks/status", "latticepeers/status", "latticepolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lattice.fullname" . }}
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lattice.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lattice.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
